#!/usr/bin/env bash
# setup-daily-reminders-bridge.sh
#
# One-time setup. Run from Terminal:
#   bash setup-daily-reminders-bridge.sh
#
# What it does:
#   1. Finds its own location (self-discovering)
#   2. Creates .reminders-runner.sh in the same folder with the absolute path baked in
#   3. Installs a LaunchAgent plist that fires .reminders-runner.sh at 6:01 AM daily

set -euo pipefail

# ── Resolve the directory this script lives in ────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNNER="$SCRIPT_DIR/.reminders-runner.sh"
GENERATED_SCRIPT="$SCRIPT_DIR/daily-apple-reminders.sh"
LOG_FILE="/tmp/daily-reminders.log"
PLIST_LABEL="com.jameson.daily-reminders"
PLIST_PATH="$HOME/Library/LaunchAgents/$PLIST_LABEL.plist"

echo "==> Setting up daily-reminders-bridge from: $SCRIPT_DIR"

# ── Write .reminders-runner.sh ────────────────────────────────────────────────
cat > "$RUNNER" <<RUNNER_SCRIPT
#!/usr/bin/env bash
# Auto-generated by setup-daily-reminders-bridge.sh — do not edit manually.
# Runs the AI-generated daily reminder script and logs output.

SCRIPT_PATH="$GENERATED_SCRIPT"
LOG="$LOG_FILE"

echo "[\$(date)] Running daily reminders..." >> "\$LOG"

if [[ -f "\$SCRIPT_PATH" ]]; then
    bash "\$SCRIPT_PATH" >> "\$LOG" 2>&1
    echo "[\$(date)] Done." >> "\$LOG"
else
    echo "[\$(date)] ERROR: \$SCRIPT_PATH not found. Was the AI agent step skipped?" >> "\$LOG"
fi
RUNNER_SCRIPT

chmod +x "$RUNNER"
echo "==> Created $RUNNER"

# ── Install LaunchAgent plist ─────────────────────────────────────────────────
mkdir -p "$HOME/Library/LaunchAgents"

cat > "$PLIST_PATH" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$PLIST_LABEL</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$RUNNER</string>
    </array>

    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>6</integer>
        <key>Minute</key>
        <integer>1</integer>
    </dict>

    <key>StandardOutPath</key>
    <string>$LOG_FILE</string>

    <key>StandardErrorPath</key>
    <string>$LOG_FILE</string>

    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
PLIST

echo "==> Installed LaunchAgent plist at $PLIST_PATH"

# ── Load the LaunchAgent ──────────────────────────────────────────────────────
# Unload first in case a stale version is already registered
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"
echo "==> LaunchAgent loaded (fires daily at 6:01 AM)"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "Setup complete!"
echo ""
echo "  Runner script : $RUNNER"
echo "  Generated daily: $GENERATED_SCRIPT  (written by AI agent at 5:30 AM)"
echo "  LaunchAgent   : $PLIST_PATH  (fires at 6:01 AM)"
echo "  Log file      : $LOG_FILE"
echo ""
echo "Next step: connect your Claude Cowork scheduled task to write"
echo "  $GENERATED_SCRIPT"
echo "each morning at 5:30 AM."
